name: Setup github action
description: Setup github action .env file

inputs:
  init_env:
    description: 'Which environment to use'
    required: true
    default: 'test'

runs:
  using: 'composite'
  steps:
    - run: cp .env.${{ inputs.init_env }}.dist .env
      shell: bash
